imdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('movie.urls', namespace='movies')),
    path('admin/', admin.site.urls),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name='movie'


urlpatterns = [
    path('', views.MovieList.as_view(), name='movie_list'),
    path('<int:pk>/', views.MovieDetail.as_view(), name='movie_detail'),
    path('category/<str:category>/', views.MovieCategory.as_view(), name='movie_category'),
    path('language/<str:lang>/', views.MovieLanguage.as_view(), name='movie_language'),
    
]

movie/models.py
from django.db import models

CATEGORY_CHOICES  = (
    ('action', 'ACTION'),
    ('drama', 'DRAMA'),
    ('comedy', 'COMEDY'),
    ('romance', 'ROMANCE')
)

LANGUAGE_CHOICES = (
    ('GR', 'GERMAN'),
    ('EN', 'ENGLISH')
)

STATUS_CHOICES = (
    ('RA', 'RECENTLY ADDED'),
    ('MW', 'MOST WATCHED'),
    ('TR', 'TOP RATED')
)

class Movie(models.Model):
    title = models.CharField(max_length=254, null=False, blank=False)
    description = models.TextField(max_length=1024)
    # tags = models.
    image = models.ImageField(upload_to='movies')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=2)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    cast = models.CharField(max_length=254)
    year_of_production = models.DateField()
    views_count = models.IntegerField(default=0)


    def __str__(self):
        return self.title

LINK_CHOICES = (
    ('D','DOWNLOAD'),
    ('W', 'WATCH')
)

class  MovieLink(models.Model):
    movie = models.ForeignKey(Movie, related_name='movie_watch_link', on_delete=models.CASCADE) 
    type = models.CharField(choices=LINK_CHOICES, max_length=1)
    link = models.URLField()

    def __str__(self):
        return self.movie.title

movie/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Movie, MovieLink


class MovieList(ListView):
    model = Movie
    paginate_by=1
    
    


class MovieDetail(DetailView):
    model = Movie
    

    def get_object(self):
        object = super(MovieDetail, self).get_object()
        object.views_count +=1
        object.save()
        return object
    

    def get_context_data(self, **kwargs):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        context['links'] = MovieLink.objects.filter(movie=self.get_object())
        return context

class MovieCategory(ListView):
    model = Movie
    paginate_by=1

    def get_queryset(self):
        self.category = self.kwargs['category']
        return Movie.objects.filter(category=self.category)

    
    def get_context_data(self, **kwargs):
        context = super(MovieCategory, self).get_context_data(**kwargs)
        context['movie_category'] = self.category
        return context


class MovieLanguage(ListView):
    model = Movie
    paginate_by=1

    def get_queryset(self):
        self.language = self.kwargs['lang']
        return Movie.objects.filter(language=self.language)

    
    def get_context_data(self, **kwargs):
        context = super(MovieLanguage, self).get_context_data(**kwargs)
        context['movie_language'] = self.language
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">




	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"></figure><a href="index.html"><img src="{% static 'img/logo.png' %}" alt="Logo"></a></figure>
			<nav class="menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="{% url 'movies:movie_category' 'action' %}">Action</a></li>
							<li><a href="{% url 'movies:movie_category' 'comedy' %}">Comedy</a></li>
							<li><a href="{% url 'movies:movie_category' 'drama' %}">Drama</a></li>
							<li><a href="{% url 'movies:movie_category' 'romance' %}">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							<li><a href="year.html">2017</a></li>
							<li><a href="year.html">2016</a></li>
							<li><a href="year.html">2015</a></li>
							<li><a href="year.html">2014</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="language.html">English</a></li>
							<li><a href="language.html">German</a></li>
						</ul>
					</li>
					
					<li class="mobsearch">
						<form class="mobform">
							<input type="text" name="s" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search">
				<input type="text" name="s" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="img/menu.svg"></div>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster1.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/poster2.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

		{% block content %}

		{% endblock %}

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		<!-- Swiper JS -->
		<script src="js/swiper.min.js"></script>

		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function(){


				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

			
		</script>


	</div>
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/movie/movie_detail.html
{% extends 'base.html' %} {% block content %}
<main class="content">
  <div class="single">
    <section class="trailer">
      <h3>Trailer</h3>
      <div class="trailer_frame">
        <iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/x73-573aWfs"
          frameborder="0"
          allowfullscreen
        ></iframe>
      </div>
    </section>

    <section class="movie">
      <img src="{{object.image.url}}" />
      <ul>
        <li>{{object}}</li>
        <li>{{object.description}}</li>
        <li>
          <a href="genre.html">Adventure</a>, <a href="genre.html">Drama</a>,
          <a href="genre.html">Romance</a>
        </li>
        <li><a href="">{{object.cast}}</a>,</li>
        <li>{{object.views_count}}</li>
      </ul>
    </section>
    <section class="links">
      <h3>Links</h3>
      <ul class="dlinks">
        <li><a>Download</a></li>
        {% for link in links %} {% if link.type == 'D' %}
        <li><a href="{{link.link}}">Link {{forloop.counter}}</a></li>
        {% endif %} {% endfor %}
      </ul>
      <ul class="wlinks">
        <li><a>Watch</a></li>
        {% for link in links %} {% if link.type == 'W' %}
        <li><a href="{{link.link}}">Link {{forloop.counter}}</a></li>
        {% endif %} {% endfor %}
      </ul>
    </section>

    <section class="related">
      <h3>Related movies</h3>
      <div class="relatemovie">
        <a href="#"><img src="images/2.jpg" /></a>
        <a href="#"><span class="relatedname">John Wick</span></a>
      </div>
      <div class="relatemovie">
        <a href="#"><img src="images/3.jpg" /></a>
        <a href="#"><span class="relatedname">Spider Man Homecoming</span></a>
      </div>
      <div class="relatemovie">
        <a href="#"><img src="images/4.jpg" /></a>
        <a href="#"><span class="relatedname">Beauty and Beast</span></a>
      </div>
      <div class="relatemovie">
        <a href="#"><img src="images/5.jpg" /></a>
        <a href="#"
          ><span class="relatedname"
            >Pirates of the Caribbean: Dead Men Tell No Tales</span
          ></a
        >
      </div>
      <div class="relatemovie">
        <a href="#"><img src="images/6.jpg" /></a>
        <a href="#"><span class="relatedname">Fifty Shades Darker</span></a>
      </div>
      <div class="relatemovie">
        <a href="#"><img src="images/7.jpg" /></a>
        <a href="#"><span class="relatedname">Transformers</span></a>
      </div>
    </section>
  </div>
</main>
{% endblock %}

templates/movie/movie_list.html
{% extends 'base.html' %} {% block content %}
<main class="content">
  <section class="centered">
    <h3>{{movie_category|title}} Movies for You</h3>
    <div class="movies">
      {% for movie in object_list %}
      <div class="mov">
        <a href="">
          <img src="{{movie.image.url}}" />
          <h2 class="movietitle">{{movie.title}}</h2>
        </a>
      </div>
      {% empty %}

      <h3>There are no movies in category!</h3>
      {% endfor %}
    </div>
    {% if is_paginated %}
    <nav class="pagination">
      <ul>
        {% if page_obj.has_previous %}
            <li><a href="?page={{page_obj.previous_page_number}}">Prev</a></li>
        {% else %}
            <li class="disabled">Prev</li>
        {% endif %}
        
        {% for pages in page_obj.paginator.page_range %}
            {% if page_obj.number == pages %}
                <li><a href="#">{{pages}}</a></li>
            {% else %}
                <li><a href="?page={{pages}}">{{pages}}</a></li>
            {% endif %}
        {% endfor %}

      
        
        
        {% if page_obj.has_next %}
            <li><a href="?page={{page_obj.next_page_number}}">Next</a></li>
        {% else %}
            <li class="disabled">Next</li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </section>
</main>

{% endblock %}